### ISSUE TITLE
Integration error with using FindKaHIP.cmake

### ISSUE THREAD

**Issue by kks32** [KaHIP/KaHIP#59]
Hi @schulzchristian Thank you so much for a great library. 

We have been using KaHIP for our MPM code (https://github.com/cb-geo/mpm) to do mesh/particle partitioning. We use a `FindKaHiP.cmake` file : https://github.com/cb-geo/mpm/blob/develop/cmake/FindKaHIP.cmake and use:

```
find_package(KaHIP REQUIRED)
if (KAHIP_FOUND)
  add_definitions("-DUSE_GRAPH_PARTITIONING")
  include_directories(${KAHIP_INCLUDE_DIRS})
  link_libraries(${KAHIP_LIBRARIES})
endif()
```

It has worked well so far. However, recent changes in KaHIP is causing problems with our FindKaHIP.cmake. I get the following error: 
```
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:137 (message):
  KaHIP could not be found/configured.  (missing: KAHIP_TEST_RUNS)
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindKaHIP.cmake:140 (find_package_handle_standard_args)
  CMakeLists.txt:106 (find_package)


-- Configuring incomplete, errors occurred!
```

I tried to narrow down the issue to a commit, but some commits fail due to `argtable2` error. 

```
git bisect start
# bad: [08f58b193cd13fad2a7123eb353a891fd570446d] fix object library
git bisect bad 08f58b193cd13fad2a7123eb353a891fd570446d
# good: [11030eef131e9f75ce16fef72e3d06f5b570059f] added licence batch
git bisect good 11030eef131e9f75ce16fef72e3d06f5b570059f
# good: [6212d611535a31ed71d265a6573e652ac06d7147] readme
git bisect good 6212d611535a31ed71d265a6573e652ac06d7147
# good: [bad52b40a8b514f34ae16539daecc6c2e62093b9] mode change
git bisect good bad52b40a8b514f34ae16539daecc6c2e62093b9
# bad: [977ab562f40d7dbdc97f175662dc2ee7d9c84187] update build script
git bisect bad 977ab562f40d7dbdc97f175662dc2ee7d9c84187
# good: [55026de0526795ca5ba02efd8f81c374aef0e806] readme ilp description
git bisect good 55026de0526795ca5ba02efd8f81c374aef0e806
# good: [17d396327fdadfe70842c7aff35ff24bdf0df0ab] cmake stuff
git bisect good 17d396327fdadfe70842c7aff35ff24bdf0df0ab
# good: [410fd52113a75a54481c2997449113c78eac5659] Readme
git bisect good 410fd52113a75a54481c2997449113c78eac5659
# bad: [c792c8bf8374a6498f0aa90cf5e46747090cd2b1] added global multisection
git bisect bad c792c8bf8374a6498f0aa90cf5e46747090cd2b1
```

I think the compilation error for us starts here or before: https://github.com/KaHIP/KaHIP/commit/977ab562f40d7dbdc97f175662dc2ee7d9c84187

Your help would be greatly appreciated! Many thanks!!

**Comment by schulzchristian** [comment]
Not sure how I can help :)
did you try ``make install'' in the current build of KaHIP?
The test says it doesnt find KaHIP -- shouldn't this be an installation error?

Best
Christian

**Comment by DanielSeemaier** [comment]
Hi, 

I think that this might be due to 5594f1dc04894dfc21262d114337247d23eadae9 (copies libinterface.so to deploy/libkahip.so), causing `find_library` in your `FindKaHIP.cmake` to find the shared library rather than the static one, hence the test case cannot be run because the `deploy/` directory is probably not in your `LD_LIBRARY_PATH`. 

Could you try changing 

```  find_library(KAHIP_LIBRARY kahip
    HINTS ${KAHIP_ROOT}/deploy $ENV{KAHIP_ROOT}/deploy /usr/local/KaHIP/deploy
    NO_DEFAULT_PATH
    DOC "Directory where the KaHIP library is located"
  )```
to 

```  find_library(KAHIP_LIBRARY libkahip.a
    HINTS ${KAHIP_ROOT}/deploy $ENV{KAHIP_ROOT}/deploy /usr/local/KaHIP/deploy
    NO_DEFAULT_PATH
    DOC "Directory where the KaHIP library is located"
  )```

and see if that works? 

Best
Daniel

**Comment by kks32** [comment]
Thanks sorry to bother you. Yes, in both cases it installs fine.

The version that works is: `78d2bb0a2c8cb396fed45710a4292034fffdaf83` and has the following files:
![image](https://user-images.githubusercontent.com/3963513/95342576-18965c80-08a7-11eb-916d-a6915a1071f8.png)

while the master has the following files:

![image](https://user-images.githubusercontent.com/3963513/95342681-3794ee80-08a7-11eb-839f-330566232173.png)

When I try to run with the newer KaHIP, I'm unable to find `libinterface`:

```
/mpm: error while loading shared libraries: libinterface.so: cannot open shared object file: No such file or directory
./mpm: error while loading shared libraries: libinterface.so: cannot open shared object file: No such file or directory
./mpm: error while loading shared libraries: libinterface.so: cannot open shared object file: No such file or directory
./mpm: error while loading shared libraries: libinterface.so: cannot open shared object file: No such file or directory
```

am I missing linking to a library with the newer version? This is what I pick up using `CMake`

```
-- Found KaHIP: /home/krishna/workspace/kahip/deploy/libkahip.so;/home/krishna/workspace/kahip/deploy/libparhip.a;/home/krishna/workspace/kahip/deploy/parallel/libkahip.a 
```

**Comment by kks32** [comment]
Sorry Daniel I just saw your comment. I'll try that

**Comment by kks32** [comment]
Thank you so much @DanielSeemaier ! your suggestion worked perfectly!

```
find_library(KAHIP_LIBRARY libkahip.a
    HINTS ${KAHIP_ROOT}/deploy $ENV{KAHIP_ROOT}/deploy /usr/local/KaHIP/deploy
    NO_DEFAULT_PATH
    DOC "Directory where the KaHIP library is located"
  )
```

Thanks again @DanielSeemaier and @schulzchristian !!
